name: Generate Snake Animation

on:
  schedule:
    # Runs at 5 AM IST every day
    - cron: "0 23 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: rashmikanth-tech
          outputs: dist/snake.svg

      - name: Push the Snake Animation to the output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
